import { useCallback, useEffect, useMemo, useState } from 'react';
import AppScreen from '../ui/AppScreen'; import AppHeader from '../ui/AppHeader'; import FinancialHero from '../ui/FinancialHero'; import Section from '../ui/Section'; import VestiPrompt from '../ui/VestiPrompt'; import PortfolioChart from '../components/PortfolioChart'; import TodaySignals from '../features/today/TodaySignals'; import TodayTimeline, { TimelineItem } from '../features/today/TodayTimeline'; import TodayNextSteps from '../features/today/TodayNextSteps'; import { useApp } from '../context/AppContext'; import { fetchQuotes, getCachedQuotes, Quote } from '../api/brapi'; import { computePortfolioStats } from '../utils/portfolio'; import { computeHealthScoreDetailed, CoachAction } from '../utils/healthCoach'; import { fmtBRL } from '../utils/format';
// CommonJS keeps the pure timeline executable by the Node regression suite.
const { buildTodayTimeline } = require('../features/today/timeline');

export default function DashboardScreen({ navigation }: any) {
  const { user, activeWallet, privacyMode, togglePrivacy, profile, snapshots, operations, proventos, recordSnapshot } = useApp();
  const [quotes, setQuotes] = useState<Record<string, Quote>>({}); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (force = false) => { const symbols = (activeWallet?.assets || []).filter((a) => ['acao', 'fii', 'etf'].includes(a.type)).map((a) => a.symbol); if (!symbols.length) { setQuotes({}); return; } if (!force) { const cached = await getCachedQuotes(symbols); setQuotes(Object.fromEntries(cached.map((q) => [q.symbol, q]))); } const fresh = await fetchQuotes(symbols, { force }); setQuotes(Object.fromEntries(fresh.map((q) => [q.symbol, q]))); }, [activeWallet]);
  useEffect(() => { load(); }, [load]);
  const onRefresh = async () => { setRefreshing(true); await load(true); setRefreshing(false); };
  const prices = Object.fromEntries(Object.entries(quotes).map(([symbol, quote]) => [symbol, quote.regularMarketPrice])); const stats = computePortfolioStats(activeWallet?.assets || [], prices); const health = computeHealthScoreDetailed(activeWallet?.assets || [], stats.profitPct, profile);
  useEffect(() => { if (stats.totalCurrent > 0) recordSnapshot(stats.totalCurrent, stats.totalInvested); }, [stats.totalCurrent, stats.totalInvested, recordSnapshot]);
  const month = new Date().toISOString().slice(0, 7); const timeline = useMemo(() => buildTodayTimeline({ operations, proventos, month }) as TimelineItem[], [operations, proventos, month]);
  const monthlyBuys = operations.filter((o) => o.date.startsWith(month) && o.type === 'buy').reduce((sum, o) => sum + o.quantity * o.price, 0); const monthlyIncome = proventos.filter((p) => p.date.startsWith(month)).reduce((sum, p) => sum + p.amount, 0); const cashFlow = monthlyIncome - monthlyBuys;
  const hour = new Date().getHours(); const greeting = `${hour < 12 ? 'Bom dia' : hour < 18 ? 'Boa tarde' : 'Boa noite'}${user?.name ? `, ${user.name.split(' ')[0]}` : ''}`;
  const handleCoachAction = (action: CoachAction) => { const lower = action.title.toLowerCase(); if (lower.includes('aporte')) navigation.navigate('Aporte'); else if (lower.includes('ativo') || lower.includes('divers')) navigation.navigate('Investir'); else navigation.navigate('Planejar'); };
  return <AppScreen refreshing={refreshing} onRefresh={onRefresh}><AppHeader eyebrow={greeting} title="Como você está hoje?" subtitle="Sua vida financeira em uma visão clara." onAvatar={() => navigation.navigate('Settings')} onNotifications={() => navigation.navigate('Alerts')} /><FinancialHero label="Patrimônio" value={fmtBRL(stats.totalCurrent)} change={stats.profitPct} changeLabel="desde seus aportes" privacyMode={privacyMode} onTogglePrivacy={togglePrivacy}>{snapshots.length > 1 ? <PortfolioChart data={snapshots.map((s) => ({ date: s.date, total: s.total }))} privacyMode={privacyMode} height={150} /> : null}</FinancialHero><TodaySignals cashFlow={cashFlow} profitPct={stats.profitPct} healthScore={health.score} /><VestiPrompt contextLabel="seu resumo financeiro" onPress={() => navigation.navigate('AIHub', { context: { source: 'today' } })} /><Section title="Seu mês até aqui" description="Movimentos organizados em ordem cronológica."><TodayTimeline items={timeline} onAdd={() => navigation.navigate('Investir', { screen: 'Operacoes' })} /></Section><Section title="Próximos passos" description="Escolhidos a partir dos seus dados atuais."><TodayNextSteps actions={health.actions} onSelect={handleCoachAction} /></Section></AppScreen>;
}
