import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import AppScreen from '../ui/AppScreen'; import AppHeader from '../ui/AppHeader'; import Section from '../ui/Section'; import Surface from '../ui/Surface'; import { palette, radii, space, typeScale } from '../theme/tokens';

const primary = [
  { label: 'Planejar aporte', description: 'Distribua seu próximo investimento.', icon: 'add-circle-outline', route: 'Aporte' },
  { label: 'Minhas metas', description: 'Acompanhe patrimônio e renda futura.', icon: 'flag-outline', route: 'Goals' },
  { label: 'Renda futura', description: 'Projete sua meta de dividendos.', icon: 'trending-up-outline', route: 'DividendTarget' },
] as const;
const tools = [
  { label: 'Imposto de renda', description: 'Apure operações e DARF.', icon: 'calculator-outline', route: 'IRAutomatico' },
  { label: 'Declaração anual', description: 'Organize os dados do IRPF.', icon: 'document-text-outline', route: 'Declaracao' },
  { label: 'Relatórios', description: 'Exporte uma visão da carteira.', icon: 'bar-chart-outline', route: 'Relatorios' },
  { label: 'Simular estratégia', description: 'Compare cenários históricos.', icon: 'git-compare-outline', route: 'Backtest' },
] as const;
function ActionRow({ item, onPress }: { item: typeof primary[number] | typeof tools[number]; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityLabel={`${item.label}. ${item.description}`} onPress={onPress} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.icon}><Ionicons name={item.icon} size={20} color={palette.brand} /></View><View style={styles.copy}><Text style={styles.label}>{item.label}</Text><Text style={styles.description}>{item.description}</Text></View><Ionicons name="chevron-forward" size={18} color={palette.inkMuted} /></Pressable>; }
export default function PlanningScreen({ navigation }: any) { return <AppScreen><AppHeader eyebrow="Seu futuro" title="Planejar" subtitle="Transforme seus objetivos em próximos passos possíveis." onAvatar={() => navigation.navigate('Settings')} /><Surface tone="brandSoft"><Text style={styles.heroLabel}>Plano do mês</Text><Text style={styles.heroTitle}>Aporte com intenção</Text><Text style={styles.heroText}>Revise suas metas e escolha onde o próximo valor pode fazer mais diferença.</Text><ActionRow item={primary[0]} onPress={() => navigation.navigate(primary[0].route)} /></Surface><Section title="Seus objetivos">{primary.slice(1).map((item) => <ActionRow key={item.route} item={item} onPress={() => navigation.navigate(item.route)} />)}</Section><Section title="Ferramentas" description="Cálculos e documentos quando você precisar."><Surface style={styles.list}>{tools.map((item) => <ActionRow key={item.route} item={item} onPress={() => navigation.navigate(item.route)} />)}</Surface></Section></AppScreen>; }
const styles = StyleSheet.create({ heroLabel: { color: palette.brand, fontSize: typeScale.label, fontWeight: '800', textTransform: 'uppercase' }, heroTitle: { color: palette.ink, fontSize: typeScale.title, fontWeight: '800', marginTop: space.xs }, heroText: { color: palette.inkSecondary, fontSize: typeScale.body, lineHeight: 21, marginTop: space.sm, marginBottom: space.md }, list: { paddingVertical: space.xs }, row: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: space.md, paddingVertical: space.md, paddingHorizontal: space.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.divider }, icon: { width: 38, height: 38, borderRadius: radii.md, backgroundColor: palette.canvasRaised, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, label: { color: palette.ink, fontSize: typeScale.bodyLarge, fontWeight: '700' }, description: { color: palette.inkSecondary, fontSize: typeScale.label, marginTop: 2 }, pressed: { opacity: 0.65 } });
